name: TagBot
on:
  schedule:
    - cron: "* * * * *"
  issues:
    types: [opened, reopened]
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${GITHUB_CONTEXT}
