on:
  schedule:
    - cron: '* * * * *'
  issues:
    types: [opened, reopened]
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
run: |
  echo "$GITHUB_CONTEXT"
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo ${GITHUB_CONTEXT}
