name: Build and Deploy in Staging
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
on:
  release:
    types:
      - edited
      - prereleased
      - released
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: set git config
      run: |
        echo $GITHUB_CONTEXT
        
        

